# Generated by Django 3.1.1 on 2021-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.CharField(blank=True, max_length=256, verbose_name='Question Details'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='reporter_email',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='Report Email'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='reporter_name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Reporter Name'),
        ),
    ]
