# Generated by Django 3.1.1 on 2021-07-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210727_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='result',
            new_name='answers',
        ),
    ]
