# Generated by Django 3.1.1 on 2021-08-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted instance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active instance')),
                ('sku', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Product SKU')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Product Name')),
                ('details', models.CharField(blank=True, max_length=256, verbose_name='Product Details')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
